name: Install Python with uv

inputs:
  python-version:
    description: Python version
    required: true

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "0.4.15"
        enable-cache: true
    - name: Install Dependencies
      run: uv sync
      shell: bash
